<a href="https://colab.research.google.com/github/Dannapaola1225/ejercicios1/blob/main/Eliminaci%C3%B3n%20gaussiana%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np

def eliminacion_gaussiana(A, b):
    """
    Realiza la eliminación gaussiana con sustitución hacia atrás para resolver Ax = b,
    mostrando todas las matrices intermedias.

    :param A: Matriz de coeficientes (numpy array de dimensión n x n).
    :param b: Vector de términos independientes (numpy array de dimensión n).
    :return: Vector solución x (numpy array de dimensión n).
    """
    n = len(b)
    A = np.array(A, dtype=float)  # Asegurar cálculos con flotantes
    b = np.array(b, dtype=float)  # Asegurar cálculos con flotantes
    #imprimimos matriz dada
    print("Matriz Inicial:")
    print(np.hstack((A, b.reshape(-1, 1))))
    # Inicializar la lista de matrices intermedias
    matrices_intermedias = []
    matrices_intermedias.append(np.hstack((A.copy(), b.reshape(-1, 1))))

    # Proceso de eliminación gaussiana
    for i in range(n):
        # Encontrar el mayor pivote absoluto en la columna actual
        max_row_index = np.argmax(abs(A[i:, i])) + i
        if A[max_row_index, i] == 0:
            raise ValueError("El sistema no tiene solución única (pivote nulo encontrado).")

        # Intercambiar la fila actual con la fila del mayor pivote
        if i != max_row_index:
            A[[i, max_row_index]] = A[[max_row_index, i]]
            b[[i, max_row_index]] = b[[max_row_index, i]]

        # Eliminar los elementos debajo del pivote
        for j in range(i + 1, n):
            factor = A[j, i] / A[i, i]
            A[j, i:] -= factor * A[i, i:]
            b[j] -= factor * b[i]

        # Almacenar la matriz intermedia
        matrices_intermedias.append(np.hstack((A.copy(), b.reshape(-1, 1))))

    # Sustitución hacia atrás
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i + 1:], x[i + 1:])) / A[i, i]

    print("\nMatriz Aumentada después de la sustitución hacia atrás:")
    print(np.hstack((A, b.reshape(-1, 1))))
# Sustitución hacia atrás
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i + 1:], x[i + 1:])) / A[i, i]

    # Almacenar la matriz final
    matrices_intermedias.append(np.hstack((A.copy(), b.reshape(-1, 1))))

    return x, matrices_intermedias


if __name__ == "__main__":
    A = [
        [1, -1, 2, -1],
        [2, -2, 3, -3],
        [1, 1, 1, 0],
        [1, -1, 4, 3]
    ]
    b = [-8, -20, -2, 4]


    try:
        resultado, matrices = eliminacion_gaussiana(A, b)
        print("\nSolución del sistema:")
        for i in range(len(resultado)):
            print(f"x{i+1} = {resultado[i]:.1f}")

        print("\nMatrices intermedias:")
        for idx, matriz in enumerate(matrices):
            print(f"\nMatriz {idx + 1}:")
            print(matriz)
    except ValueError as e:
        print("Error:", e)

Matriz Inicial:
[[  1.  -1.   2.  -1.  -8.]
 [  2.  -2.   3.  -3. -20.]
 [  1.   1.   1.   0.  -2.]
 [  1.  -1.   4.   3.   4.]]

Matriz Aumentada después de la sustitución hacia atrás:
[[  2.   -2.    3.   -3.  -20. ]
 [  0.    2.   -0.5   1.5   8. ]
 [  0.    0.    2.5   4.5  14. ]
 [  0.    0.    0.   -0.4  -0.8]]

Solución del sistema:
x1 = -7.0
x2 = 3.0
x3 = 2.0
x4 = 2.0

Matrices intermedias:

Matriz 1:
[[  1.  -1.   2.  -1.  -8.]
 [  2.  -2.   3.  -3. -20.]
 [  1.   1.   1.   0.  -2.]
 [  1.  -1.   4.   3.   4.]]

Matriz 2:
[[  2.   -2.    3.   -3.  -20. ]
 [  0.    0.    0.5   0.5   2. ]
 [  0.    2.   -0.5   1.5   8. ]
 [  0.    0.    2.5   4.5  14. ]]

Matriz 3:
[[  2.   -2.    3.   -3.  -20. ]
 [  0.    2.   -0.5   1.5   8. ]
 [  0.    0.    0.5   0.5   2. ]
 [  0.    0.    2.5   4.5  14. ]]

Matriz 4:
[[  2.   -2.    3.   -3.  -20. ]
 [  0.    2.   -0.5   1.5   8. ]
 [  0.    0.    2.5   4.5  14. ]
 [  0.    0.    0.   -0.4  -0.8]]

Matriz 5:
[[  2.   -2.    3.   -3.  -20. 