<a href="https://colab.research.google.com/github/Dannapaola1225/ejercicios1/blob/main/Factorizaci%C3%B3n%20LU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np

def factorizacion_LU(A):
    n = len(A)
    # Matrices inicializadas
    L = np.eye(( n))
    U = np.zeros((n, n))
    for i in range(n):
    #comprobamos que si se puede realizar la factorización (1)
      if A[i][i]==0:
        raise ValueError("factorización imposible")

    #calculamos primera fila y primera columna de L y U respectivamente  (2)
    #primera fila de u
    for j in range(n):
        U[0, j] = A[0, j]  # Primera fila de U
    for i in range(n):
        L[i, 0] = A[i, 0] / U[0, 0]  # Primera columna de L

    # Paso 3 y siguientes: Calcular el resto de L y U
    #seleccionamos L y U para satisfacer la igualdad (4)
    for i in range(1, n):
        if A[i, i] == 0:
            raise ValueError("Factorización imposible: pivote nulo.")

        for j in range(i, n):  # Calcular elementos de U
            U[i, j] = A[i, j] - sum(L[i, k] * U[k, j] for k in range(i))

        for j in range(i + 1, n):  # Calcular elementos de L
            L[j, i] = (A[j, i] - sum(L[j, k] * U[k, i] for k in range(i))) / U[i, i]

        if U[i,i]==0:
            raise ValueError("la matriz es singular")
    return L, U


In [19]:
def eliminacion_gaussiana(A, b):
    n = len(b)
    A = np.array(A, dtype=float)  # Asegurar cálculos con flotantes
    b = np.array(b, dtype=float)  # Asegurar cálculos con flotantes

    # Inicializar la lista de matrices intermedias
    matrices_intermedias = []
    matrices_intermedias.append(np.hstack((A.copy(), b.reshape(-1, 1))))

    # Proceso de eliminación gaussiana
    for i in range(n):
        # Encontrar el mayor pivote absoluto en la columna actual
        max_row_index = np.argmax(abs(A[i:, i])) + i
        if A[max_row_index, i] == 0:
            raise ValueError("El sistema no tiene solución única (pivote nulo encontrado).")

        # Intercambiar la fila actual con la fila del mayor pivote
        if i != max_row_index:
            A[[i, max_row_index]] = A[[max_row_index, i]]
            b[[i, max_row_index]] = b[[max_row_index, i]]

        # Eliminar los elementos debajo del pivote
        for j in range(i + 1, n):
            factor = A[j, i] / A[i, i]
            A[j, i:] -= factor * A[i, i:]
            b[j] -= factor * b[i]

        # Almacenar la matriz intermedia
        matrices_intermedias.append(np.hstack((A.copy(), b.reshape(-1, 1))))

    # Sustitución hacia atrás
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i + 1:], x[i + 1:])) / A[i, i]

    print("\nMatriz Aumentada después de la sustitución hacia atrás:")
    print(np.hstack((A, b.reshape(-1, 1))))
# Sustitución hacia atrás
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i + 1:], x[i + 1:])) / A[i, i]

    # Almacenar la matriz final
    matrices_intermedias.append(np.hstack((A.copy(), b.reshape(-1, 1))))

    return x, matrices_intermedias


In [17]:
# En este aaprtado se ingresan los valores iniciales
if __name__ == "__main__":
    A = np.array([[1, 1, 0, 3], [2, 1, -1, 1], [3, -1, -1, 2], [-1, 2, 3, -1]], dtype=float)
    b = np.array([4, 1, -3, 4], dtype=float)
    try:
        L, U = factorizacion_LU(A)
        print("Factorización LU")
        print("Matriz A:")
        print(A)
        print("Matriz L resultante:")
        print(L)
        print("Matriz U resultante:")
        print(U)

        x, matrices_intermedias = eliminacion_gaussiana(A, b)
        print("\nSolución del sistema por el étodo de sustitución hacia atrás hacia atrás:")
        resultado= x
        for i in range(len(resultado)):
            print(f"x{i+1} = {resultado[i]:.1f}")



    except ValueError as e:
        print("Error:", e)

Factorización LU
Matriz A:
[[ 1.  1.  0.  3.]
 [ 2.  1. -1.  1.]
 [ 3. -1. -1.  2.]
 [-1.  2.  3. -1.]]
Matriz L resultante:
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 3.  4.  1.  0.]
 [-1. -3.  0.  1.]]
Matriz U resultante:
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]

Matriz Aumentada después de la sustitución hacia atrás:
[[ 3.00000000e+00 -1.00000000e+00 -1.00000000e+00  2.00000000e+00
  -3.00000000e+00]
 [ 0.00000000e+00  1.66666667e+00  2.66666667e+00 -3.33333333e-01
   3.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -3.00000000e+00  5.55111512e-17
   4.44089210e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  2.60000000e+00
   2.60000000e+00]]

Solución del sistema por el étodo de sustitución hacia atrás hacia atrás:
x1 = -1.0
x2 = 2.0
x3 = -0.0
x4 = 1.0
