<a href="https://colab.research.google.com/github/Dannapaola1225/ejercicios1/blob/main/Numpi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Libreria Numpy**
*Tutorial*


La libreria **NUMPY** especializa principalmente el la realización de cálculos mátematicos, númericos, científicos y en el análisis de datos en grandes cantidades.
Es de gran útilidad para realizar operaciones matemáticas. lleva a cabo operaciones en matrices al igual de cuadros multidimencionales entre mas cosas.
puede ser utilizado como un eficiente contenedor multidimensional de datos genéricos.

***Numpy*** emplea una clase de objetos multidimencionales de nombre **arrays** los cuales permiten representar colecciones de datos de un mismo tipo de varias dimenciónes y funciones para su manipulación.

**¿que es un array?**
Es una estructura de datos de un mismo tipo organizada en forma de lista similares a las que se manejan en python las cuales pueden tener distintas dimenciones o ejes.



In [ ]:
import numpy as np

lista = [1, 2, 3]

np.array(lista)

array([1, 2, 3])

 *En este apartado tomamos una lista normal y con la función ***np.array(...)***, la convertimos en un arreglo de esta libreria*

**Dimenciones de los arrays**\
 La dimención que tendra el array, va a  depender de las listas o tuplas anidadas en en la primera.

las dimenciones pueden estar anidadas a cualquier cantidd de listas aumentando sus dimenciones sin  un limite establecido.


* Para una lista de valores se crea un array de una dimensión, también conocido como vector.

* Para una lista de listas de valores se crea un array de dos dimensiones, también conocido como matriz.

* Para una lista de listas de listas de valores se crea un array de tres dimensiones, también conocido como cubo.



In [ ]:
import numpy as np
l1=np.array([1,2,3]) #array con una dimensión
print(l1)

[1 2 3]


In [ ]:
import numpy as np
l2=np.array([[1,2,3],[4,5,6]]) #array con dos demensiones
print(l2)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
l3=np.array([[[1,2,3],[4,5,6],[7,8,9]]]) #array con tres demensiones
print(l3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


rango de números
arange toma dos números y devuelve un arreglo de números enteros que son mayores o iguales a (>=) el primer número y menores que (<) el segundo número.

In [3]:
import numpy as np
np.arange(0,6)# arroja los valores entre los intervalos


array([0, 1, 2, 3, 4, 5])

arroja los valores cada 4 valor

In [4]:
import numpy as np
np.arange(1,20,4) #

array([ 1,  5,  9, 13, 17])

 Crea y devuelve una referencia a un array con las dimensiones especificadas en la tupla dimensiones cuyos elementos son todos ceros.

In [8]:
import numpy as np
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

 Crea y devuelve una referencia a la matriz identidad de dimensión n

In [9]:
import numpy as np
np.identity((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Crea y devuelve una referencia a un array con las dimensiones especificadas en la tupla dimensiones cuyos elementos son todos unos.

In [10]:
np.ones((5))

array([1., 1., 1., 1., 1.])

Matriz inversa