<a href="https://colab.research.google.com/github/Dannapaola1225/ejercicios1/blob/main/pivoteo%20parcial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***pivoteo parcial***

In [3]:
import numpy as np

def pivoteo_parcial(A, b):

    n = len(A)# filas
    A = np.array(A, dtype=float)  # Asegurar cálculos con flotantes
    b = np.array(b, dtype=float)  # Asegurar cálculos con flotantes

    #imprime la matriz aumentada
    print("Matriz Inicial:")
    print(np.hstack((A, b.reshape(-1, 1))))

    # Iniciamos el proceso de eliminación gaussiana con pivoteo parcial
    for i in range(n):
        # Determinamos el pivote
        p = np.argmax(np.abs(A[i:, i])) + i
        if A[p, i] == 0:
            raise ValueError("El sistema no tiene solución única")

        # Intercambiamos la posición de las filas si es necesario
        if i != p:
            A[[i, p]] = A[[p, i]]
            b[[i, p]] = b[[p, i]]

        # Eliminar los elementos por debajo del pivote
        for j in range(i + 1, n):
            m = A[j, i] / A[i, i]
            A[j, i:] -= m * A[i, i:]
            b[j] -= m * b[i]

        # Imprimimos la matriz después de la eliminación de cada columna
        print(f"\nMatriz después de la eliminación en la columna {i + 1}:")
        print(np.hstack((A, b.reshape(-1, 1))))

    # Realizamos la Sustitución hacia atrás
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i + 1:], x[i + 1:])) / A[i, i]

    return x

if __name__ == "__main__":
    #matriz de coeficientes y vector independiente dados
    A = [
        [0.003000, 59.14],
        [5.291, -6.130]
    ]
    b = [59.17, 46.78]

    try:
        resultado = pivoteo_parcial(A, b)
        print("\nEl resultado obtenido es:")
        for i in range(len(resultado)):
            print(f"x{i+1} = {resultado[i]:.5f}")
    except ValueError as e:
        print("Error:", e)


Matriz Inicial:
[[ 3.000e-03  5.914e+01  5.917e+01]
 [ 5.291e+00 -6.130e+00  4.678e+01]]

Matriz después de la eliminación en la columna 1:
[[ 5.291      -6.13       46.78      ]
 [ 0.         59.14347571 59.14347571]]

Matriz después de la eliminación en la columna 2:
[[ 5.291      -6.13       46.78      ]
 [ 0.         59.14347571 59.14347571]]

El resultado obtenido es:
x1 = 10.00000
x2 = 1.00000
